recreate resources when chart values change
hashicorp/terraform-provider-helm pull request #123
Opened 2018-10-05 14:10 UTC by niroliyanage

2018-10-17 13:56 UTC, meyskens commented on helm/resource_release.go
> +							ForceNew:    true,
The values here are computed, so `ForceNew` is of no use here

2018-10-17 13:59 UTC, meyskens commented
Thanks for your PR! I don't really see why `ForceNew` is needed for new values? `ForceNew` will delete the release and recreate here, in this case I think an `helm upgrade` should be enough for a values change. 
Would love to hear your reasoning on this.

2018-10-17 13:59 UTC, meyskens requested changes
Thanks for your PR! I don't really see why `ForceNew` is needed for new values? `ForceNew` will delete the release and recreate here, in this case I think an `helm upgrade` should be enough for a values change.
Would love to hear your reasoning on this.

2018-10-23 05:22 UTC, niroliyanage commented
There are instances where we dont manage the helm charts. there are a few use cases for us that  we only need to change the values forcing the recreation of the resource using the new values automatically. We have another CI platform maintaining the change orchestration. If this defeats the purpose i can get around this by maintaining our own charts repo.

ATM, adding new values would essentially compute the new values and modifies the resource and then manual intervention is required to update it

2018-10-23 16:02 UTC, rporres commented
@niroliyanage We cannot force a new resource just because we're changing values. That would mean outage for already deployed releases where we just want a rolling upgrade.

If you want that behaviour, you can just change whatever you need and taint your resource to force recreation, but it should not be the default way of doing things.

2018-10-23 16:02 UTC, closed without merging