set connection_timeout parameter
hashicorp/terraform-provider-helm pull request #374
Opened 2019-11-07 10:48 UTC by mgar

As a solution for both #355 and #308, I added a new parameter to set the timeout in seconds to the Helm client.

This PR could be closed in favour of #359 if you think that closing the tunnel each time is the preferred solution

2019-11-07 13:10 UTC, macytd approved these changes

2019-11-07 20:09 UTC, jakesyl commented
Tbh, this is a good stop gap either way.

2019-11-07 20:12 UTC, jakesylvestre requested changes

2019-11-07 20:12 UTC, jakesyl commented on helm/provider.go
> +				Description: "Number of seconds Helm will wait to establish a connection to tiller.",
I think "Number of seconds Helm will wait before timing out a connection to tiller." is more accurate here. This makes it sound like a wait

2019-11-07 20:12 UTC, jakesyl commented on website/docs/index.html.markdown
> +* `connection_timeout` - (Optional) Number of seconds Helm will wait to establish a connection to tiller. Defaults to `5`.
This should be 60. It's inconsistent with the actual default [here](https://github.com/terraform-providers/terraform-provider-helm/pull/374/files#diff-9f0ddb4b472596921b8dc5a236a017b2R81)

2019-11-08 09:13 UTC, mgar commented on website/docs/index.html.markdown
> +* `connection_timeout` - (Optional) Number of seconds Helm will wait to establish a connection to tiller. Defaults to `5`.
good catch!

2019-11-10 10:15 UTC, meyskens commented
Thanks for the PR! Even if we go for what was done in #359 I think this is a must to have configurable.

2019-11-10 10:15 UTC, meyskens approved these changes

2019-11-10 10:15 UTC, merged

2020-01-17 22:16 UTC, grugnog commented
@meyskens any chance we could tag a new release including this fix?