Redirect klog to write to file instead of stderr to avoid blocking
hashicorp/terraform-provider-helm pull request #505
Opened 2020-05-26 19:05 UTC by pepov

### Description

Redirects klog to file instead of stderr to avoid blocking.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch? (If so, please include the test log in a gist)

I've ran the suite and it failed with a seemingly unrelated issue, that maybe connected to:
https://github.com/terraform-providers/terraform-provider-helm/issues/494

The log output:
https://gist.github.com/pepov/1b53980c5389df3ac3451c74585070da

### References
This is the original issue that this PR is trying to work around:
https://github.com/terraform-providers/terraform-provider-helm/issues/498

2020-05-28 09:27 UTC, pepov commented
sorry for the mentions, but could someone please help pointing me to someone who would possibly be willing to take a look at this pr and the underlying issue as **it's a blocker on EKS** @mcuadros @jrhouston 

https://github.com/terraform-providers/terraform-provider-helm/issues/498

2020-06-06 14:42 UTC, krzysztof-miemiec commented
Your PR, combined with my PR (https://github.com/hashicorp/terraform-provider-helm/pull/525) seems to work "in production" - I guess that my solution is not the most optimal, but hey.. it works after all! 😄🎉

2020-06-08 02:32 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-helm?pullRequest=505)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-helm?pullRequest=505)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-helm?pullRequest=505).</sub>

2020-06-09 02:50 UTC, jtyr commented
I can confirm that this PR combined together with the PR #525 solved my problem with the stuck helm provider! :heart:

2020-06-15 04:49 UTC, jrhouston requested changes
Ouch, this is a nasty bug. Thanks a lot for investigating this @pepov! There is definitely a deeper problem here that I'm going to investigate - if there is a problem with klog writing to stderr then this could surface in the other kubernetes providers too. 

For now we can accept this as a bandaid to stop the provider from hanging. The branch just needs to be rebased as we just moved this repo and there's some path conflicts.

2020-06-15 08:41 UTC, pepov commented
@jrhouston rebased on master, thx for looking into this!

2020-06-15 19:46 UTC, jrhouston approved these changes

2020-06-15 19:46 UTC, merged