Upgrade helm to v3.6.1
hashicorp/terraform-provider-helm pull request #761
Opened 2021-06-17 15:39 UTC by jrhouston

### Description

Bumping the helm version as per #760 

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-helm/blob/main/CHANGELOG.md):

```release-note
...
```
### References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

2021-06-28 20:12 UTC, dak1n1 approved these changes
Tested locally. Looks good, thanks!

2021-06-29 15:54 UTC, redeux requested changes
Please hold this PR.  There is a regression in v3.6.1

2021-07-08 16:50 UTC, dak1n1 approved these changes
Dependencies look good, and it works in testing. Thanks!

2021-07-08 16:59 UTC, redeux requested changes

2021-07-08 16:59 UTC, redeux commented on CHANGELOG.md
> +* Upgrade helm to 3.6.1
Needs to be updated as well

2021-07-08 17:01 UTC, redeux approved these changes

2021-07-23 04:47 UTC, merged